# DOCKERFILE AUTOGENERATED BY hack-toolchain
FROM rust:1.79.0-alpine
RUN apk update
RUN apk add vim alpine-sdk zig
RUN rustup component add rustfmt
RUN rustup component add clippy
RUN rustup toolchain install nightly
RUN rustup target add aarch64-apple-darwin
RUN cargo install --locked cargo-zigbuild
WORKDIR /local
